set_property SRC_FILE_INFO {cfile:c:/Users/062062/Desktop/trimode_example/xc7z020clg400_example/rgmii_example/gmii_to_rgmii_0_ex/imports/gmii_to_rgmii_0_example_design.xdc rfile:../../../imports/gmii_to_rgmii_0_example_design.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18       [get_ports clkin]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   H18     [get_ports rgmii_rxc]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN    J18    [get_ports mdio_phy_mdio]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {core_wrapper/i_gmii_to_rgmii/U0/rgmii_rxc_ibuf}]
