# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/bae_io.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_versal_cips_0_0/design_1_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_versal_cips_0_0 || ORIG_REF_NAME==design_1_versal_cips_0_0} -quiet] -quiet

# Block Designs: c:/Users/062062/Desktop/test_git/aw/vmk180_bae/vmk180_bae.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da || ORIG_REF_NAME==bd_70da} -quiet] -quiet

# IP: c:/Users/062062/Desktop/test_git/aw/vmk180_bae/vmk180_bae.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] -quiet

# IP: c:/Users/062062/Desktop/test_git/aw/vmk180_bae/vmk180_bae.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_noc_0_0 || ORIG_REF_NAME==design_1_axi_noc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wizard_0_0/design_1_clk_wizard_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wizard_0_0 || ORIG_REF_NAME==design_1_clk_wizard_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dbg_hub_0_0/design_1_axi_dbg_hub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dbg_hub_0_0 || ORIG_REF_NAME==design_1_axi_dbg_hub_0_0} -quiet] -quiet

# XDC: c:/Users/062062/Desktop/test_git/aw/vmk180_bae/vmk180_bae.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/062062/Desktop/test_git/aw/vmk180_bae/vmk180_bae.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_3/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/062062/Desktop/test_git/aw/vmk180_bae/vmk180_bae.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da_ooc.xdc

# XDC: c:/Users/062062/Desktop/test_git/aw/vmk180_bae/vmk180_bae.gen/sources_1/bd/design_1/design_1_ooc.xdc
