# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/test/vmk180_bae/vmk180_bae.srcs/sources_1/ip/axis_ila_0/axis_ila_0.xci
# IP: The module: 'axis_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/bd_30f1_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0 || ORIG_REF_NAME==bd_30f1_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_0/bd_30f1_0_axis_dbg_stub_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_stub_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_stub_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_1/bd_30f1_0_xlconstant_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_xlconstant_0 || ORIG_REF_NAME==bd_30f1_0_xlconstant_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_2/bd_30f1_0_axis_ila_intf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_ila_intf_0 || ORIG_REF_NAME==bd_30f1_0_axis_ila_intf_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_3/bd_30f1_0_axis_cap_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_cap_ctrl_0 || ORIG_REF_NAME==bd_30f1_0_axis_cap_ctrl_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_4/bd_30f1_0_axis_mu0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_mu0_0_0 || ORIG_REF_NAME==bd_30f1_0_axis_mu0_0_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_5/bd_30f1_0_axis_dbg_sync_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_2_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_2_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_6/bd_30f1_0_axis_dbg_sync_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_3_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_3_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_7/bd_30f1_0_axis_dbg_sync_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_4_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_4_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_8/bd_30f1_0_axis_dbg_sync_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_5_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_5_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_9/bd_30f1_0_axis_dbg_sync_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_6_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_6_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_10/bd_30f1_0_tc_axis_mu0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_tc_axis_mu0_0 || ORIG_REF_NAME==bd_30f1_0_tc_axis_mu0_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_11/bd_30f1_0_cc_axis_mu0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu0_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu0_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_12/bd_30f1_0_cc_axis_mu1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu1_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu1_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_13/bd_30f1_0_cc_axis_mu2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu2_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu2_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_14/bd_30f1_0_cc_axis_mu3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu3_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu3_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_15/bd_30f1_0_axis_itct_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_itct_0 || ORIG_REF_NAME==bd_30f1_0_axis_itct_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_16/bd_30f1_0_axis_ila_pp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_ila_pp_0 || ORIG_REF_NAME==bd_30f1_0_axis_ila_pp_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_17/bd_30f1_0_axis_mem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_mem_0 || ORIG_REF_NAME==bd_30f1_0_axis_mem_0} -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_4/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_mu0_0_0 || ORIG_REF_NAME==bd_30f1_0_axis_mu0_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_10/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_tc_axis_mu0_0 || ORIG_REF_NAME==bd_30f1_0_tc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_11/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu0_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_12/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu1_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_13/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu2_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_14/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu3_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/bd_30f1_0_ooc.xdc

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/axis_ila_v1_2/constraints/axis_ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/axis_ila_v1_2/constraints/axis_ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/axis_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.srcs/sources_1/ip/axis_ila_0/axis_ila_0.xci
# IP: The module: 'axis_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/bd_30f1_0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0 || ORIG_REF_NAME==bd_30f1_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_0/bd_30f1_0_axis_dbg_stub_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_stub_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_stub_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_1/bd_30f1_0_xlconstant_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_xlconstant_0 || ORIG_REF_NAME==bd_30f1_0_xlconstant_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_2/bd_30f1_0_axis_ila_intf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_ila_intf_0 || ORIG_REF_NAME==bd_30f1_0_axis_ila_intf_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_3/bd_30f1_0_axis_cap_ctrl_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_cap_ctrl_0 || ORIG_REF_NAME==bd_30f1_0_axis_cap_ctrl_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_4/bd_30f1_0_axis_mu0_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_mu0_0_0 || ORIG_REF_NAME==bd_30f1_0_axis_mu0_0_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_5/bd_30f1_0_axis_dbg_sync_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_2_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_2_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_6/bd_30f1_0_axis_dbg_sync_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_3_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_3_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_7/bd_30f1_0_axis_dbg_sync_4_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_4_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_4_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_8/bd_30f1_0_axis_dbg_sync_5_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_5_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_5_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_9/bd_30f1_0_axis_dbg_sync_6_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_dbg_sync_6_0 || ORIG_REF_NAME==bd_30f1_0_axis_dbg_sync_6_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_10/bd_30f1_0_tc_axis_mu0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_tc_axis_mu0_0 || ORIG_REF_NAME==bd_30f1_0_tc_axis_mu0_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_11/bd_30f1_0_cc_axis_mu0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu0_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu0_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_12/bd_30f1_0_cc_axis_mu1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu1_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu1_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_13/bd_30f1_0_cc_axis_mu2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu2_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu2_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_14/bd_30f1_0_cc_axis_mu3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu3_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu3_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_15/bd_30f1_0_axis_itct_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_itct_0 || ORIG_REF_NAME==bd_30f1_0_axis_itct_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_16/bd_30f1_0_axis_ila_pp_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_ila_pp_0 || ORIG_REF_NAME==bd_30f1_0_axis_ila_pp_0} -quiet] -quiet

# IP: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_17/bd_30f1_0_axis_mem_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_mem_0 || ORIG_REF_NAME==bd_30f1_0_axis_mem_0} -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_4/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_axis_mu0_0_0 || ORIG_REF_NAME==bd_30f1_0_axis_mu0_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_10/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_tc_axis_mu0_0 || ORIG_REF_NAME==bd_30f1_0_tc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_11/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu0_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_12/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu1_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_13/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu2_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/ip/ip_14/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_30f1_0_cc_axis_mu3_0 || ORIG_REF_NAME==bd_30f1_0_cc_axis_mu3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/bd_0/bd_30f1_0_ooc.xdc

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/axis_ila_v1_2/constraints/axis_ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/axis_ila_v1_2/constraints/axis_ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/test/vmk180_bae/vmk180_bae.gen/sources_1/ip/axis_ila_0/axis_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
